// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vospmdkmjoegttsuqjbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvc3BtZGttam9lZ3R0c3VxamJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTgxODMsImV4cCI6MjA2NTU5NDE4M30.CXc_QFsQITs56kgi662NcPIIHxan7cp4LsxDfW6hebM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);